import {
  IconLayoutDashboard,
  IconCirclePlus,
  IconPlus,
  IconFileText,
  IconSettings,
  IconSearch,
  IconBell,
  IconHelpCircle,
  IconChevronLeft,
  IconChevronRight,
  IconChevronDown,
  IconMenu2,
  IconDownload,
  IconCheck,
  IconChecks,
  IconCircleCheck,
  IconPencil,
  IconBan,
  IconMessage,
  IconFlag,
  IconBook,
  IconX,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowDown,
  IconArrowsSort,
  IconColumns,
  IconArrowBackUp,
  IconLockOpen,
  IconDots,
  IconBarrierBlock,
  IconShieldExclamation,
  IconAlertCircle,
  IconAlertTriangle,
  IconInfoCircle,
  IconUser,
  IconMinus,
  IconSparkles,
  IconClipboardCheck,
  IconLayoutSidebarLeftCollapse,
  IconLayoutSidebarLeftExpand,
  IconSun,
  IconMoon,
  IconDeviceDesktop,
  IconLogout,
  IconLifebuoy,
  IconAdjustmentsHorizontal,
  IconListCheck,
  IconTemplate,
  IconBuilding,
  IconCalendar,
  IconClock,
  IconFileTypePdf,
  IconCircleX,
  IconBrandWindows,
  IconBrandGoogle,
  IconPlugConnected,
  IconShieldLock,
  IconRocket,
  IconGavel,
  IconEye,
  IconQuote,
  IconUpload,
  IconTrash,
  IconRefresh,
  IconArrowsSplit2,
  IconCloudUpload,
  IconCopy,
  IconHistory,
  type Icon as TablerIcon,
} from "@tabler/icons-react";

export const ICONS = {
  dashboard: IconLayoutDashboard,
  order: IconCirclePlus,
  add: IconPlus,
  templates: IconTemplate,
  document: IconFileText,
  settings: IconSettings,
  search: IconSearch,
  bell: IconBell,
  help: IconHelpCircle,
  "chevron-left": IconChevronLeft,
  "chevron-right": IconChevronRight,
  "chevron-down": IconChevronDown,
  menu: IconMenu2,
  download: IconDownload,
  check: IconCheck,
  "check-all": IconChecks,
  "check-circle": IconCircleCheck,
  edit: IconPencil,
  reject: IconBan,
  comment: IconMessage,
  flag: IconFlag,
  book: IconBook,
  close: IconX,
  back: IconArrowLeft,
  forward: IconArrowRight,
  "arrow-up": IconArrowUp,
  "arrow-down": IconArrowDown,
  sort: IconArrowsSort,
  columns: IconColumns,
  undo: IconArrowBackUp,
  unlock: IconLockOpen,
  more: IconDots,
  construction: IconBarrierBlock,
  crit: IconShieldExclamation,
  fail: IconAlertCircle,
  warn: IconAlertTriangle,
  info: IconInfoCircle,
  user: IconUser,
  na: IconMinus,
  ai: IconSparkles,
  checklist: IconClipboardCheck,
  "panel-close": IconLayoutSidebarLeftCollapse,
  "panel-open": IconLayoutSidebarLeftExpand,
  sun: IconSun,
  moon: IconMoon,
  monitor: IconDeviceDesktop,
  logout: IconLogout,
  support: IconLifebuoy,
  filter: IconAdjustmentsHorizontal,
  reviews: IconListCheck,
  org: IconBuilding,
  calendar: IconCalendar,
  clock: IconClock,
  pdf: IconFileTypePdf,
  "x-circle": IconCircleX,
  "brand-windows": IconBrandWindows,
  "brand-google": IconBrandGoogle,
  connect: IconPlugConnected,
  sso: IconShieldLock,
  rocket: IconRocket,
  gavel: IconGavel,
  eye: IconEye,
  quote: IconQuote,
  upload: IconUpload,
  trash: IconTrash,
  refresh: IconRefresh,
  split: IconArrowsSplit2,
  publish: IconCloudUpload,
  copy: IconCopy,
  history: IconHistory,
} satisfies Record<string, TablerIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  size = 18,
  strokeWidth = 1.75,
  className,
  style,
}: {
  name: IconName;
  size?: number;
  strokeWidth?: number;
  className?: string;
  style?: React.CSSProperties;
}) {
  const Cmp = ICONS[name];
  return (
    <Cmp size={size} stroke={strokeWidth} className={className} style={style} />
  );
}
