import {
  LayoutDashboard,
  PlusCircle,
  Plus,
  FileText,
  Settings,
  Search,
  Bell,
  HelpCircle,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Menu,
  Download,
  Check,
  CheckCheck,
  CircleCheck,
  Pencil,
  Ban,
  MessageSquare,
  Flag,
  BookOpen,
  X,
  ArrowLeft,
  ArrowRight,
  Undo2,
  LockOpen,
  MoreHorizontal,
  Construction,
  ShieldAlert,
  CircleAlert,
  TriangleAlert,
  Info,
  User,
  Minus,
  Sparkles,
  ClipboardCheck,
  PanelLeftClose,
  PanelLeft,
  Sun,
  Moon,
  Monitor,
  LogOut,
  LifeBuoy,
  SlidersHorizontal,
  ClipboardList,
  Building2,
  CalendarDays,
  type LucideIcon,
} from "lucide-react";

export const ICONS = {
  dashboard: LayoutDashboard,
  order: PlusCircle,
  add: Plus,
  templates: FileText,
  document: FileText,
  settings: Settings,
  search: Search,
  bell: Bell,
  help: HelpCircle,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  menu: Menu,
  download: Download,
  check: Check,
  "check-all": CheckCheck,
  "check-circle": CircleCheck,
  edit: Pencil,
  reject: Ban,
  comment: MessageSquare,
  flag: Flag,
  book: BookOpen,
  close: X,
  back: ArrowLeft,
  forward: ArrowRight,
  undo: Undo2,
  unlock: LockOpen,
  more: MoreHorizontal,
  construction: Construction,
  crit: ShieldAlert,
  fail: CircleAlert,
  warn: TriangleAlert,
  info: Info,
  user: User,
  na: Minus,
  ai: Sparkles,
  checklist: ClipboardCheck,
  "panel-close": PanelLeftClose,
  "panel-open": PanelLeft,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  logout: LogOut,
  support: LifeBuoy,
  filter: SlidersHorizontal,
  reviews: ClipboardList,
  org: Building2,
  calendar: CalendarDays,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  size = 18,
  strokeWidth = 2,
  className,
  style,
}: {
  name: IconName;
  size?: number;
  strokeWidth?: number;
  className?: string;
  style?: React.CSSProperties;
}) {
  const Cmp = ICONS[name];
  return (
    <Cmp size={size} strokeWidth={strokeWidth} className={className} style={style} />
  );
}
